---
output:
  pdf_document: default
  html_document: default
---

# 损失调整 {#lossmodif}

在非寿险精算中，风险实际造成的损失和保险公司的赔款通常是不一致的。赔款可能受到保单条款的影响，主要包括：

- 免赔额
- 赔偿限额
- 共同保险
- 通货膨胀

**索赔频率**和**索赔强度**的计算就不是简单的损失次数和损失金额的计算。
  
## 免赔额对赔付金额的影响
  许多保险合同中都规定了免赔额，其目的是提高保单持有人的风险防范意识，同时减少保险公司的小额赔款，降低理赔费用。如果用 $d$ 表示免赔额，则当损失金额不超过 $d$ 时，保险公司没有任何赔款支出:而当损失金额超过 $d$ 时，保险公司的赔款为 $(x-d)$。免赔额的应用对索赔次数和赔付额都会产生影响，下面分别进行分析。

  如果用 $x$ 表示保单持有人的损失，用 $d$ 表示免赔额，用 $Y$ 表示保险公司的赔款，则对 $Y$ 可以有下述两种解释:
一种解释是保险公司对每次损失的赔款包括当保单持有人的损失不超过免赔额 $d$ 时，保险公司支付的零赔款在内。如果把$Y$ 解释为保险公司对每次损失的赔款，则 $Y$ 就是超额损失随机变量，也可以称作“含零赔款”的随机变量。该随机变量可表示为:

$$
{{Y}^{L}}={{\left( X-d \right)}_{+}}= 
\begin{cases}
  & 0,\quad \quad \quad X\le d \\ 
 & X-d,\quad X>d .
\end{cases} 
$$
含零赔款的随机变量取零值的概率（即损失不超过免赔额 $d$ 的概率）为:
$$
Pr(Y^L≤0)=Pr(X≤d)= F_x(d)
$$
$Y^L$的分布函数和密度函数分别为:
$$
F_{Y^L}(y)= Pr(Y^L≤y)=Pr(X- d≤y)=Pr(X≤y+d)=F_x(y+d)，y>0$$
$$
f_{Y^L}(y)= f_x(y+d)， y>0
$$
对赔款随机变量的另一种解释是保险公司发生的“非零赔款”，或者说是与保险公司的每次支付行为相对应的赔款，不包括当保单持有人的损失不超过免赔额 $d$ 时，保险公司无须支付的零赔款。如果把 $Y$ 解释为保险公司每次支付行为所发生的赔款，则 $Y$ 就是“非零赔款”的随机变量。该随机变量可表示为:
$$Y^P=X-d | X>d$$
上式表明，$Y^P$ 是一个条件随机变量，只有当 $X>d$ 时, $Y^P$ 才有定义。
$Y^P$ 的分布函数和密度函数分别为:
$$
F_{Y^P}(y)=Pr(Y^{P}≤y|X>d)
=Pr(X-d≤y|X>d)
=\frac {Pr(0<X-d≤y)}{Pr(X>d)}
=\frac{F_x (y+d)-F_x(d) }{1-F_x (d)}， y>0
$$
$$f_{Y^P}(y)=\frac{ f_{x}(y+d)}{1-F_{X}(d)}， y>0$$

定理：当一般免赔额为$d$ 时，含零赔款的均值为$E({Y}^{L})=E(X)-E({X}\wedge {d})$，非零赔款的均值为：
$$
E(Y^P)=\frac{\mathbb{E}(X)-\mathbb{E}(X\wedge d)}{1-F_{X}(d)}
$$


## 通货膨胀对赔付金额的影响
定理：如果一般免赔额为 $d$，均匀的通货膨胀率为 $r$，则平均含零赔款为：
$$
E(Y^L)=(1+r)\left\{
\mathbb{E}(X) - \mathbb{E}(X \wedge \frac{d}{1+r})
\right\}
$$
例：损失服从$\alpha=3,\theta=2000$ 的帕累托分布，讨论免赔额为$500$，通货膨胀率为 $10%$ 时对损失的影响。

答案：平均含零赔款为$640$，平均非零赔款为 $1250$ ，当通货膨胀率为 $10%$ 时：
$$
\begin{align*}
\mathbb{E}\left(X \wedge \frac{500}{1.1}\right) &= 
\mathbb{E}(X \wedge 454.55)=336.08.
\end{align*}
$$
通货膨胀后的平均含零赔款为： $1.1(1,000 - 336.08) = 730.32$，增加了$14.11%$。 
$$
F_Y(500)=0.459.
$$
平均非零赔款为： $730.32/(1 - 0.459) = 1,350$， 增长了 $8%$。


## 赔偿限额对赔付金额的影响

赔偿限额的作用与免赔额正好相反。在免赔额条件下，保险公司对低于免赔额的损失不予赔偿，而在赔偿限额条件下，保险公司对高于赔偿限额的损失不予赔偿。换言之，赔偿限额是保险公司对一次索赔的最大可能赔款。如果赔偿限额为 $u$，则当损失低于$u$ 时，保险公司将全部赔偿，而当损失超过$u$ 时，保险公司只赔偿 $u$。赔偿限额的作用是生成一个“右删改”随机变量，即将超过 $u$ 的损失全部修改为 $u$。
假设 $x$ 表示实际损失的随机变量，$Y$ 表示应用赔偿限额 $u$ 所生成的随机变量，则 $Y$ 的分布函数和密度函数分别为:

$$
F_Y(y)=\begin{cases}
F_X(y),\quad & y \le u,\\
1, \quad & y>u,
\end{cases}
$$

$$
f_Y(y)=\begin{cases}
f_X(y),\quad & y \le u,\\
1-F_X(u), \quad & y>u.
\end{cases}
$$
如果赔偿限额为 $u$，均匀的通货膨胀率为 $r$，则保险公司的平均赔款可表示为:
$$
E({Y}\wedge {U})=(1+r)\mathbb{E}[X\wedge \frac{u}{1+r}]
$$

如果保单的免赔额为 $d$，赔偿限额为 $u-d$，则保险公司的赔款为:

$$
Y=\begin{cases}
   0 \ \ \ \ \ &X\le d \\ 
  X-d,\ \ \ &d<X<u \\ 
  u-d,\ \ \ \ &X\ge u \\ 
\end{cases} 
$$
例：假设某险种的保单规定绝对免赔额为$100$元，保单赔偿限额为$900$元。假设损失服从 $Weibull$ 分布：

$$
F(x)=1-{{e}^{- {{{(x/\theta)}}{}^{\tau }}}},x>0,\theta >0,\tau >0
$$

求理赔额 $Y^P$ 的分布函数。


答案：假设 $X$ 表示实际损失额， $Y^P$ 表示理赔额（非零），则有

$$
{{Y}^{P}}=\left\{ \begin{matrix}
   \begin{matrix}
   {NA}  \\
   X-100,  \\
   900,  \\
\end{matrix} & \begin{matrix}
   X\le 100  \\
   100<X\le 1000  \\
   X>1000  \\
\end{matrix}  \\
\end{matrix} \right.
$$

$Y^P$ 的分布函数为

$$
{{F}_{Y}}(y)=\left\{ \begin{matrix}
   \begin{matrix}
   0,  \\
   \frac{{{F}_{X}}(y+100)-{{F}_{X}}(100)}{1-{{F}_{X}}(100)},  \\
   1,  \\
\end{matrix} & \begin{matrix}
   y=0  \\
   0<y\le 900  \\
   y\ge 900  \\
\end{matrix}  \\
\end{matrix} \right.
$$

$Y^P$ 的密度函数为

$$
{{f}_{{{Y}^{P}}}}(y)=\left\{ \begin{matrix}
   \begin{matrix}
   \frac{{{f}_{X}}(y+100)}{1-{{F}_{X}}(100)}, & \text{   }0\le y<900  \\
\end{matrix}  \\
   \begin{matrix}
   \frac{1-{{F}_{X}}(1000)}{1-{{F}_{X}}(100)}\text{,  } & y=900  \\
\end{matrix}  \\
   \begin{matrix}
   0,\text{                   } & y>900  \\
\end{matrix}  \\
\end{matrix} \right.\text{        }
$$

当$y = 900$时，

$$
{{f}_{{{Y}^{p}}}}(900)=\frac{1-{{F}_{X}}(1000)}{1-{{F}_{X}}(100)}=\frac{\exp [-{{(1000/ \theta )}^{\tau }}]}{\exp [-{{(100/ \theta )}^{\tau }}]}
$$

当$0\le y<900$时，


$$
{{f}_{{{Y}^{P}}}}(y)=\frac{{{f}_{X}}(y+100)}{1-{{F}_{X}}(100)}=\frac{{{(1/\theta) }^{\tau }}\tau {{(y+100)}^{\tau -1}}\exp [-{{(1/\theta) }^{\tau }}{{(y+100)}^{\tau }}]}{\exp [-{{(100/ \theta )}^{\tau }}]}
$$


## 共同保险对赔付金额的影响

共同保险是指对每一次损失，保险公司只赔偿一定的比例，如$100\alpha%$，而保单持有人自负剩余的损失。如果保险合同中只规定了共同保险，则保险公司的赔款随机变量可以表示为$Y=\alpha X$,其中 $X$ 为保单持有人的实际损失，在这种情况下，保险公司的平均赔款为$E(Y)=\alpha E(X)$。

下面讨论一种更加具有一般性的随机变量，即实际损失$X$ 经通货膨胀 $(r)$、赔偿限额 $（u）$、一般免赔额 $（d）$ 和共同保险 $（\alpha）$ 调整后保险公司的赔款随机变量。此时，保险公司的含零赔款 $Y^L$ 可以表示为下述的随机变量:
$$
Y^L=\begin{cases}
0，\quad & X<\frac{d}{1+r}\\
\alpha[(1+r)X-d]， \quad & \frac{d}{1+r}\le X < \frac{u}{1+r}\\
\alpha(u-d)，\quad & X \ge \frac{u}{1+r}
\end{cases}
$$
在上述定义中，假设对实际损失的调整是按照一个特定顺序进行的，即首先进行通货膨胀调整，再使用赔偿限额，然后应用免赔额，最后才是共同保险。由于赔偿限额在免赔额之前应用，所以，保险公司的最大可能赔款为$\alpha(u-d)$。如果用 $Y^P$ 表示保险公司的非零赔款随机变量，则当 $X < \frac{d}{1+r}$ 时，$Y^P$ 没有定义。
可以证明，当实际损失X按照通货膨胀 $(r)$、赔偿限额 $(u)$、一般免赔额 $(d)$ 和共同保险 $(α)$ 的顺序调整以后，其含零赔款 $Y^L$ 的均值为:
$$
\mathbb{E}(Y^L)=\alpha(1+r)\left[
\mathbb{E}\left(X \wedge \frac{u}{1+r}\right)-
\mathbb{E}\left(X \wedge \frac{d}{1+r}\right)
\right]
$$
对于非零赔款 $Y^P$，其均值为：
$$
\mathbb{E}(Y^p) = \frac{\mathbb{E}(Y^L)}{1-F_X\left(\frac{d}{1+r} \right)}
$$


例：今年，当 $d = 10,11,12,.. .,26$ 时，损失分布服从 ：
$$
\mathbb{E}[X\wedge d]=-0.025d^2+1.475d-2.25
$$


明年，每年的通货膨胀率为10%，免赔额为11，保险最多报销11，求明年报销的与今年报销金额的比值。
=======
for $d = 10,11,12,.. .,26$. 

Next year, losses will be uniformly higher by 10\%. An
insurance policy reimburses 100\% of losses subject to a deductible of 11 up to a maximum
reimbursement of 11. 

Determine the ratio of next year's reimbursements to this year's
reimbursements.

The quantity we seek is


答案：
$$
\frac{1.1[\mathbb{E}[X\wedge 22/1.1]-\mathbb{E}[X\wedge 11/1.1]]}{\mathbb{E}[X\wedge 22]-\mathbb{E}[X\wedge 11]}
=1.115
$$

## 免赔额对索赔次数的影响

在前面的讨论中，我们用 $N$ 表示实际发生的损失次数。现在考虑增加免赔额$d$ 以后，保单持有人的索赔次数 $N^*$。假设增加免赔额不会影响损失发生的过程。
显然，对于任何一次实际发生的损失 $X$，只有当它大于免赔额 $d$ 时，保单持有人才会提出索赔。因此保单持有人提出索赔的概率(也是保险公司发生赔付的概率)为:
=======
在前面的讨论中，我们用N表示实际发生的损失次数。现在考虑增加免赔额d以后，保单持有人的索赔次数N*。假设增加免赔额不会影响损失发生的过程。
显然，对于任何一次实际发生的损失X，只有当它大于免赔额d时，保单持有人才会提出索赔。因此保单持有人提出索赔的概率(也是保险公司发生赔付的概率)为:

$$\upsilon=Pr(X>d)$$
如果用 $I_j = 1$ 表示第j次损失导致了索赔，用 $I_j=0$ 表示第$j$ 次损失没有导致索赔，则$I_j$就是服从参数为 $\upsilon$ 的贝努利分布，而索赔次数$N^*$可以表示为:
$$N^*=I_1+...+I_N$$
如果假设$I_j$相互独立，同时与$N$ 也相互独立，则$N^*$ 是一个复合分布，其中首分布就是损失次数$N$ 的分布，而次分布是参数为$\upsilon$ 的贝努利分布。因此
$$P_{N^*}(z)=P_N[1+\upsilon (z-1)]$$
可以证明，增加免赔额以后,$(a,b,0)$ 分布类和$(a,b,1)$ 都能保持其原来的形式不变，只是其参数的取值发生了变化。

例1:
证明：若损失次数是泊松 $\lambda$，则索赔次数也是泊松 $v\lambda$。

答案：
损失次数： 
$$
P_{N^L}(z)=\exp[{\lambda}{(z-1)}]
$$

索赔次数:
$$
\begin{align*}
P_{N^P}(z)&=\exp[{v\lambda}(z-1)]\\
&=P_{N^L}[1+v(z-1)]\\
&=\exp[\lambda(1+ v(z-1)-1)]\\
&=\exp[{v\lambda}{(z-1)}]
\end{align*}
$$

例2:
证明：如果损失次数 $N^L$ 服从负二项分布，参数为 $(r,\beta)$。

答案：
$$
P_{N^L}(z)=[1-{\beta}{(z-1)}]^{-r}
$$

索赔次数 $N^P$  仍然服从负二项分布，参数为$(r,v\beta)$：
$$
\begin{align*}
P_{N^P}(z)&=P_{N^L}[1+v(z-1)]\\
&=[1-\beta(1+v(z-1)-1)]^{-r}\\
&=[1-{v\beta}{(z-1)}]^{-r}
\end{align*}
$$


以下是$(a,b,0)$分布的索赔次数在增加免赔额后其对应参数取值发生的变化:

  | $N^L$ | 母函数 | $N^P$ |
  | :----: | :----: | :----: |
  | 泊松($\lambda$)  | $exp[\lambda (z-1)]$ | $\lambda ^*=v\lambda$ |
  | 二项($m,q$)  | ${[1+q(z-1)]}^m$ | $m^*=m,q^*=vq$ |
  | 负二项($r,\beta$)  | ${[1-\beta (z-1)]}^{-r}$ | $r^*=r,\beta ^*=v\beta$ |
  
例3:  
损失金额服从帕累托分布，参数为$\alpha=3，\theta=1000$，损失次数服从负二项分布，参数为$r=2，\beta=3$，求免赔额为250时损失次数服从的分布及参数。

答案：
$N^p$ 一定服从负二项分布，对应参数为 $r^* =r$ ，$\beta^* = v\beta$。

其中：
$$
v = 1-F(250)=0.512,
$$
即$r^* =2$，$\beta^* = 1.536$。


## 课后习题

1.
某家公司购买了一份商业保险，财产保险的限额为70000，某次事故发生时财产的实际价值为100000，该保险的共同保险为80%，免赔额为200，免赔额优先于共同保险和限额考虑，实际损失为20000，求此次损失中保险公司的赔款。

2.
1993年，损失的概率密度函数为$f(x)=e^x,x>0$，1993年至1994年的通货膨胀率为5%，每年的赔偿限额为1，在考虑限额的情况下，求1993年至1994年的通货膨胀率。

3.
假设损失服从$\sigma$=2.5, $\theta$=1000的单参数帕累托分布，赔偿限额为5000，求平均含零赔款。

4.
损失的分布函数为：
$$
F(x)=1-0.8e^{-0.02x}-0.2e^{-0.001x},x\ge0
$$
每次损失的赔偿限额为1000，求赔款的期望。

5.
已知：
1）$E(X\wedge x)$= 500-1000000/x ，x > 2000；
2）赔偿限额为10000；
3）通货膨胀率为25%。
求通货膨胀后的期望赔款和通货膨胀前的期望赔款的比率。

6.
损失的概率密度函数为：
$$f_{x}(x) = 0.02x , 0 < x < 10$$
当免赔额为4时求平均非零赔款。

7.
损失的概率密度函数为：$f(x)=2x,0<x<1$，当免赔额为$d$时，索赔金额小于0.5的概率为0.64，求$d$的值，其中$0<d<1$。

8.
已知如下的损失相关的数据：


  |损失金额 | 损失次数 | 总损失金额 |
  | :----: | :----: | :----: |
  | 0-99  | 1100 | 58,500 |
  | 100-247  | 400 | 70,000 |
  | 250-499  | 300 | 120,000 |
  | 500-999  | 200 | 150,000 |
  | >999  | 100 | 200,000 |
  | Total  | 2100 | 598,500 |
  
  
计算当免赔额从100变成250时，损失减少了多少百分比。
