--- 
title: "非寿险精算与风险模型"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---


# 课程简介 {#prep}

这是对外经济贸易大学和西南财经大学开设《非寿险精算学》等课程的讲义， 其中使用了其它教材的例子和讲法， 仅供学生内部使用， 不作为公开出版。 鉴于本人水平有限， 错漏之处难免，欢迎指出错误或提出改进意见。

***编写人员***：

- 李政宵（对外经济贸易大学保险学院副教授）

- 杨亮（西南财经大学金融学院副教授）

- 刘坤（对外经济贸易大学 2020 级硕士生）

- 刘雅薇（对外经济贸易大学 2020 级硕士生）

## 课程内容

本课程是一门三学分课程（精算与风险管理专业必修、其他专业选修），适合风险管理、保险与精算等相关专业的**本科高年级学生**参考。 

非寿险精算主要内容是**风险模型**、**费率厘定**和**准备金评估**。

- **风险模型**：风险度量、索赔次数模型、索赔金额模型、累积损失模型
- **费率厘定**：分类费率厘定、经验费率厘定
- **准备金评估**：未到期责任准备金、未决赔款准备金、理赔费用准备金评估

在教学过程中中，以 **R 语言** 为编程工具，同时提供了详细的程序代码，方便读者再现完整的编程和计算过程。


## 先修内容
需要概率论与数理统计、高等数学、线性代数、保险学的基础知识

- **概率论与数理统计**：随机变量、概率分布、中心极限定理
- **高等数学**：微积分、泰勒公式
- **线性代数**：矩阵运算
- **保险学**：基本概念和专业术语


## 教材和参考资料

- Klugman S. A., Panjer H. H., Willmot G. E. Loss models: from data to decisions (5th edition).  London: John Wiley & Sons, 2016.

- 孟生旺、刘乐平、肖争艳、高光远, 非寿险精算学（第4版），人民大学出版社，2019年.

- 孟生旺, 《风险模型》, 中国人民大学出版社，2022.

- 肖争艳，《精算模型》（第三版），中国人民大学出版社，2019.

## R 软件与 Rmarkdown 简介

<<<<<<< HEAD
## R 软件与 Rmarkdown 可视化
=======
<!-- ### R 软件 -->
>>>>>>> a9c1af5f1208bfcaf624a9e1290d70db00030d56

- R 软件是用于统计计算和绘图的免费软件环境。
安装 R 软件的步骤主要分下述几步步：

  - [安装 R 软件](https://cran.r-project.org/)
  
  
  - [安装 RStudio](https://posit.co/download/rstudio-desktop/)。RStudio 是一款 R 语言的 IDE（集成开发环境），操作界面简洁美观。
  
  - [安装 rtools](https://mirrors.tuna.tsinghua.edu.cn/CRAN/)。rtools 是 R 软件在构建和编译包所需要的编译工具。

<!-- ### rmarkdown 简介 -->

- ``Rmarkdown`` 是 R 语言环境中提供的 markdown 编辑工具。可以用来创建富有格式和互动性的文档。它可以让用户将代码、文本、图表等内容组合到一个文档中，以生成多种格式的输出，如 HTML、PDF、Word 文档等。``Rmarkdown`` 的作用包括：



<!-- rmarkdown 的简易教程如下： -->

<!-- - 在 RStudio 新建一个 rmarkdown 文件后，会出现如下一个最简单的 rmarkdown 的模板。 -->

<!-- 增加rmarkdown的介绍、安装和使用说明，包括如何导出html和pdf格式，介绍一些简答的公式输入 -->



